name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project files
        run: ls -la

      - name: Build backend image
        run: docker build -t docker-lab-backend ./backend

      - name: Build frontend image
        run: docker build -t docker-lab-frontend ./frontend

      - name: Start application
        run: docker compose up -d
        continue-on-error: true

      - name: Check application status
        run: docker compose ps

      - name: Show database logs
        run: docker compose logs db
