on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
       POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
       POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
       POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show project files
        run: ls -la

      - name: Build backend image
        run: docker build -t gagan681/docker-lab-backend:latest ./backend

      - name: Push backend image
        run: docker push gagan681/docker-lab-backend:latest

      - name: Build frontend image
        run: docker build -t docker-lab-frontend ./frontend

      - name: Start application
        run: docker compose up -d
        continue-on-error: true

      - name: Test backend health
        run: curl --fail http://localhost:8000/health

      - name: Check frontend
        run: |
         sleep 5
         curl --fail http://localhost:3000

      - name: Check application status
        run: docker compose ps

      - name: Show database logs
        run: docker compose logs db

      - name: Stop application
        if: always()
        run: docker compose down
